from __future__ import annotations

from typing import TYPE_CHECKING

IS_PROD = False
DEBUG_EAGER_EXEC = True
DEBUG_CALLBACK = False
DEBUG_USE_QUICK_MODE = True
DEBUG_QUICK_EVO_MODE = True
DEBUG_PRINT_PRECISION = 4
DEBUG_QUICK_TRAIN = False
DEBUG_USE_MOCK = False
DEBUG_SKIP_DYNAMICS = True if not IS_PROD else False
DEBUG_SKIP_VIZ = True if not IS_PROD else False
FIX_BINARY_OFFSET = 1
DEBUG_DISTRIBUTION = False
DEBUG_DATASET = False
READER = "OutcomeDice4ELReader"
MUTATION_RATE_STAGE_1 = [0.01, 0.01, 0.01, 0.01, 0.01]
MAX_ITER_STAGE_1 = 100
MAX_ITER_STAGE_2 = 50
MAX_ITER_STAGE_3 = 50
# MAX_ITER_STAGE_SPECIAL = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
STEP_SIZE = 10
MAX_ITER_STAGE_SPECIAL = 200
# print(f">>>>>>>>>>>{MAX_ITER_STAGE_SPECIAL}<<<<<<<<<<<<<<<<<<<<<")
